/**
 * Every neutral camp, from the game's minimap artwork. Generated by
 * scripts/gen-minimap-icons.py; do not edit.
 *
 * `side` is the half of the map it is on ("amber", "sapphire"), or "lane" for the two
 * tier 3 camps out on the side lanes. `x`/`y` are world units.
 */
export type CampSite = {
  name: string
  side: 'amber' | 'sapphire' | 'lane'
  tier: 1 | 2 | 3
  x: number
  y: number
}

export const CAMP_SITES: CampSite[] = [
  {"name": "Drug Store", "side": "amber", "tier": 1, "x": 1372, "y": -999},
  {"name": "Port Authority", "side": "amber", "tier": 1, "x": -7304, "y": -1340},
  {"name": "Baroness Hotel", "side": "sapphire", "tier": 1, "x": -1499, "y": 872},
  {"name": "Speakeasy", "side": "sapphire", "tier": 1, "x": 7219, "y": 1233},
  {"name": "Alley #1", "side": "amber", "tier": 2, "x": -2009, "y": -797},
  {"name": "Alley #2", "side": "amber", "tier": 2, "x": -3285, "y": -1244},
  {"name": "Asylum", "side": "amber", "tier": 2, "x": 7921, "y": -4710},
  {"name": "Bodega", "side": "amber", "tier": 2, "x": -5093, "y": -1669},
  {"name": "Church", "side": "amber", "tier": 2, "x": 7985, "y": -2371},
  {"name": "Factory", "side": "amber", "tier": 2, "x": -5539, "y": -3860},
  {"name": "Fishmarket #1", "side": "amber", "tier": 2, "x": 5773, "y": -1776},
  {"name": "Fishmarket #2", "side": "amber", "tier": 2, "x": 4476, "y": -2052},
  {"name": "Garage", "side": "amber", "tier": 2, "x": -3881, "y": -1329},
  {"name": "Rooftop", "side": "amber", "tier": 2, "x": -6879, "y": -2307},
  {"name": "Statue", "side": "amber", "tier": 2, "x": 2180, "y": -4008},
  {"name": "Tenements", "side": "amber", "tier": 2, "x": -2350, "y": -5008},
  {"name": "Alley", "side": "sapphire", "tier": 2, "x": -8049, "y": 4625},
  {"name": "Alley #1", "side": "sapphire", "tier": 2, "x": 1924, "y": 776},
  {"name": "Alley #2", "side": "sapphire", "tier": 2, "x": 3222, "y": 1095},
  {"name": "Firehouse", "side": "sapphire", "tier": 2, "x": -8049, "y": 2520},
  {"name": "Gallery Rooftop", "side": "sapphire", "tier": 2, "x": 6815, "y": 2158},
  {"name": "Garage", "side": "sapphire", "tier": 2, "x": 3817, "y": 1393},
  {"name": "Nursery", "side": "sapphire", "tier": 2, "x": -4561, "y": 1903},
  {"name": "Nursery Rooftop", "side": "sapphire", "tier": 2, "x": -5858, "y": 1627},
  {"name": "Palace", "side": "sapphire", "tier": 2, "x": 5518, "y": 3902},
  {"name": "Statue", "side": "sapphire", "tier": 2, "x": -2350, "y": 3626},
  {"name": "Theater", "side": "sapphire", "tier": 2, "x": 5008, "y": 1180},
  {"name": "Warehouse", "side": "sapphire", "tier": 2, "x": 2265, "y": 5008},
  {"name": "Armory", "side": "amber", "tier": 3, "x": -3604, "y": -4455},
  {"name": "Clinic Alley #1", "side": "amber", "tier": 3, "x": 1053, "y": -3137},
  {"name": "Clinic Alley #2", "side": "amber", "tier": 3, "x": 2265, "y": -2988},
  {"name": "Garment Center Alley", "side": "amber", "tier": 3, "x": 3966, "y": -4264},
  {"name": "Taxi Stand", "side": "amber", "tier": 3, "x": -5093, "y": -755},
  {"name": "Greenwich", "side": "lane", "tier": 3, "x": 9261, "y": 11},
  {"name": "York", "side": "lane", "tier": 3, "x": -9176, "y": -11},
  {"name": "Law Firm Alley #1", "side": "sapphire", "tier": 3, "x": -1159, "y": 2988},
  {"name": "Law Firm Alley #2", "side": "sapphire", "tier": 3, "x": -3285, "y": 2073},
  {"name": "Police Alley", "side": "sapphire", "tier": 3, "x": -4072, "y": 4136},
  {"name": "Taxi Stand", "side": "sapphire", "tier": 3, "x": 4987, "y": 521},
  {"name": "Warehouse", "side": "sapphire", "tier": 3, "x": 3541, "y": 4455},
]
