/**
 * Map metadata. Generated by scripts/gen-map-image.mjs; do not edit.
 *
 * The playable area is a disc of this many world units about the origin. The map image
 * reaches a little further -- see MAP_IMAGE_RADIUS in ./index.ts, which is what a
 * position is actually measured against.
 */
export const MAP_RADIUS = 10752
