"""
Mirror the neutral-camp and Urn markers from the game's minimap artwork.

The minimap source (MINIMAP_3-7.psd and its COMPS folder, from the game's own artwork)
places every neutral camp as a named layer -- "AMBER | Factory", in a group per tier --
and draws the Urn's pickup and its drop-off. This reads both and commits the result:

  src/map/camps.ts              every camp: name, side, tier, and world position
  src/assets/map/urn-pickup.webp
  src/assets/map/urn-dropoff-team.webp
  src/assets/map/urn-dropoff-enemy.webp

Camps are placed by the artwork's own coordinates, converted to world units with one
transform calibrated on the two points both systems know: the Urn's two spawns, which a
replay puts at x = +-6592, y = 0, and which the artwork marks with its "Left" and "Right"
pickup layers. Checked on a real match, a tier 1 camp placed this way lands within about
120 world units of where its creeps spawn -- a few pixels on a minimap.

The camp markers themselves are not mirrored: they are a triangle over zero to two bars,
simple enough to draw as vectors (see src/components/MapTimers.tsx) and so stay crisp at
any zoom. The Urn's are painted art, so they are mirrored as images.

Needs psd-tools with its compositing extras:

    pip install "psd-tools[composite]"
    python scripts/gen-minimap-icons.py "D:/map/Minimap"
"""

import io
import json
import sys
from pathlib import Path

from psd_tools import PSDImage

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / 'src' / 'assets' / 'map'
MANIFEST = ROOT / 'src' / 'map' / 'camps.ts'

#: Where a replay puts the Urn's two spawns, in world units.
URN_SPAWN_X = 6592
#: Pixel height the Urn images are kept at: the largest they are drawn, doubled for
#: high-density screens.
URN_PX = 64


def find(layers, name):
    for layer in layers:
        if layer.name == name:
            return layer
    raise SystemExit(f'no layer named {name!r}')


def centre(bbox, offset=(0, 0)):
    left, top, right, bottom = bbox
    return ((left + right) / 2 + offset[0], (top + bottom) / 2 + offset[1])


def main(source: Path):
    master = PSDImage.open(source / 'MINIMAP_3-7.psd')
    comps = source / 'COMPS'

    # Where the COMPS files sit on the master canvas.
    camps_at = find(master, 'POI | Neutrals').bbox[:2]
    urn_at = find(master, 'POI | Urn Pickup').bbox[:2]

    # The calibration: the Urn's two pickups, in canvas pixels, against their world x.
    urn = PSDImage.open(comps / 'Urn.psb')
    left = centre(find(urn, 'Left').bbox, urn_at)
    right = centre(find(urn, 'Right').bbox, urn_at)
    scale = (right[0] - left[0]) / (2 * URN_SPAWN_X)  # canvas pixels per world unit
    origin = ((left[0] + right[0]) / 2, (left[1] + right[1]) / 2)  # world (0, 0)

    def world(point):
        # The canvas's y runs down; the world's runs north.
        return (round((point[0] - origin[0]) / scale), round((origin[1] - point[1]) / scale))

    camps = []
    for group in PSDImage.open(comps / 'Camps.psb'):
        if not group.is_group() or not group.name.startswith('Tier'):
            continue
        tier = int(group.name.split()[-1])
        for layer in group:
            # "AMBER ｜ Factory" -- note the full-width bar -- or a lane name on its own.
            parts = [p.strip() for p in layer.name.replace('｜', '|').split('|')]
            side, name = (parts[0].lower(), parts[1]) if len(parts) == 2 else ('lane', parts[0].title())
            x, y = world(centre(layer.bbox, camps_at))
            camps.append({'name': name, 'side': side, 'tier': tier, 'x': x, 'y': y})
    camps.sort(key=lambda c: (c['tier'], c['side'], c['name']))

    # The Urn's art: the pickup is a smart object; the drop-offs are plain layers, one of
    # them hidden, so read from their pixels rather than composited.
    ASSETS.mkdir(parents=True, exist_ok=True)
    pickup = PSDImage.open(io.BytesIO(find(urn, 'Left').smart_object.data)).composite()
    images = {'urn-pickup': pickup.crop(pickup.getbbox())}
    for layer in PSDImage.open(comps / 'Urn_Dropoff.psb'):
        kind = layer.name.split('|')[-1].strip().lower()
        images[f'urn-dropoff-{kind}'] = layer.topil()
    for name, image in images.items():
        height = URN_PX
        width = round(image.width * height / image.height)
        image.resize((width, height)).save(ASSETS / f'{name}.webp', lossless=True)
        print(f'  {name}.webp {width}x{height}')

    rows = '\n'.join(f'  {json.dumps(c, ensure_ascii=False)},' for c in camps)
    MANIFEST.write_text(
        f'''/**
 * Every neutral camp, from the game's minimap artwork. Generated by
 * scripts/gen-minimap-icons.py; do not edit.
 *
 * `side` is the half of the map it is on ("amber", "sapphire"), or "lane" for the two
 * tier 3 camps out on the side lanes. `x`/`y` are world units.
 */
export type CampSite = {{
  name: string
  side: 'amber' | 'sapphire' | 'lane'
  tier: 1 | 2 | 3
  x: number
  y: number
}}

export const CAMP_SITES: CampSite[] = [
{rows}
]
''',
        encoding='utf-8',
    )
    print(f'  camps.ts: {len(camps)} camps, calibration {scale:.5f} px/unit at {origin}')


if __name__ == '__main__':
    main(Path(sys.argv[1] if len(sys.argv) > 1 else 'D:/map/Minimap'))
