/**
 * hero_id -> artwork slug. Generated by scripts/gen-hero-images.mjs; do not edit.
 *
 * Ids are the GC's own, so they survive a hero being renamed. The slug is the filename
 * under src/assets/heroes/{icons,portraits}/.
 */
export const HERO_SLUGS: Record<number, string> = {
  1: 'infernus', // Infernus
  2: 'seven', // Seven
  3: 'vindicta', // Vindicta
  4: 'lady-geist', // Lady Geist
  6: 'abrams', // Abrams
  7: 'wraith', // Wraith
  8: 'mcginnis', // McGinnis
  10: 'paradox', // Paradox
  11: 'dynamo', // Dynamo
  12: 'kelvin', // Kelvin
  13: 'haze', // Haze
  14: 'holliday', // Holliday
  15: 'bebop', // Bebop
  16: 'calico', // Calico
  17: 'grey-talon', // Grey Talon
  18: 'mo-krill', // Mo & Krill
  19: 'shiv', // Shiv
  20: 'ivy', // Ivy
  21: 'kali', // Kali
  25: 'warden', // Warden
  27: 'yamato', // Yamato
  31: 'lash', // Lash
  35: 'viscous', // Viscous
  38: 'gunslinger', // Gunslinger
  39: 'the-boss', // The Boss
  47: 'tokamak', // Tokamak
  48: 'wrecker', // Wrecker
  49: 'rutger', // Rutger
  50: 'pocket', // Pocket
  51: 'thumper', // Thumper
  52: 'mirage', // Mirage
  53: 'fathom', // Fathom
  54: 'cadence', // Cadence
  58: 'vyper', // Vyper
  59: 'vandal', // Vandal
  60: 'sinclair', // Sinclair
  61: 'trapper', // Trapper
  62: 'raven', // Raven
  63: 'mina', // Mina
  64: 'drifter', // Drifter
  65: 'venator', // Venator
  66: 'victor', // Victor
  67: 'paige', // Paige
  68: 'boho', // Boho
  69: 'the-doorman', // The Doorman
  70: 'skyrunner', // Skyrunner
  71: 'swan', // Swan
  72: 'billy', // Billy
  74: 'graf', // Graf
  75: 'fortuna', // Fortuna
  76: 'graves', // Graves
  77: 'apollo', // Apollo
  79: 'rem', // Rem
  80: 'silver', // Silver
  81: 'celeste', // Celeste
}
